feat: use cssnano instead of csso
sometimes csso occurs syntax error like this:

```
$ postcss 'src/style/**/[^._]*' --dir dist/style --ext css
SyntaxError: Unexpected input
    at Object.error (/app/node_modules/css-tree/lib/parser/create.js:240:19)
    at /app/node_modules/css-tree/lib/parser/create.js:299:20
    at parseToCsso (/app/node_modules/postcss-csso/lib/postcssToCsso.js:16:26)
    at postcssToCsso (/app/node_modules/postcss-csso/lib/postcssToCsso.js:69:20)
    at Array.map (<anonymous>)
    at appendChildren (/app/node_modules/postcss-csso/lib/postcssToCsso.js:10:39)
    at postcssToCsso (/app/node_modules/postcss-csso/lib/postcssToCsso.js:41:24)
    at Array.map (<anonymous>) {
  source: 'box-shadow: var(--tw- ring - inset) 0 0 0 calc(3px + var(--tw - ring - offset - width)) var(--tw - ring - color); ',
  offset: 112,
  line: 1,
  column: 113,
  sourceFragment: [Function (anonymous)],
  parseError: { offset: 112, line: 1, column: 113 }
}
error Command failed with exit code 1.
```

to prevent this, use cssnano recommended by tailwindcss

See: https://tailwindcss.com/docs/optimizing-for-production